name: Bug report
description: Report a bug and help us improve
labels:
  - bug
body:
  - type: checkboxes
    id: label_check
    attributes:
      label: Label verification (MANDATORY)
      description: Before creating this issue, you verified that the required label(s) exist. If missing, you created the label(s) first per the Constitution.
      options:
        - label: I have verified that the necessary label(s) exist or I created them
          required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
