name: Feature request
description: Suggest an idea or enhancement
labels:
  - enhancement
body:
  - type: checkboxes
    id: label_check
    attributes:
      label: Label verification (MANDATORY)
      description: Before creating this issue, you verified that the required label(s) exist. If missing, you created the label(s) first per the Constitution.
      options:
        - label: I have verified that the necessary label(s) exist or I created them
          required: true
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-sentence summary of the feature.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Describe the problem, proposed solution, and alternatives considered.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      placeholder: |
        - [ ] When X, Y happens
        - [ ] Z is updated
    validations:
      required: true
